name: Create issue on branch creation

on:
  create:
    branches:
      - '*'   # triggers on every branch creation

jobs:
  create-issue:
    runs-on: ubuntu-latest
    steps:
      - name: Create issue for new branch
        uses: peter-evans/create-issue-from-file@v5
        with:
          title: "Issue: ${{ github.ref_name }}"
          content-filepath: .github/ISSUE_TEMPLATE/branch-issue.md
          labels: Feature
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
